//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int clienteId { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> dtNascimento { get; set; }
        public string CFP { get; set; }
        public string CEP { get; set; }
        public string nrLogradouro { get; set; }
        public string telefone { get; set; }
    }
}
