//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filme
    {
        public int filmeId { get; set; }
        public string nome { get; set; }
        public Nullable<int> ano { get; set; }
        public string genero { get; set; }
        public Nullable<int> ativo { get; set; }
    }
}
