//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locacao
    {
        public int locacaoId { get; set; }
        public Nullable<int> clienteId { get; set; }
        public string filmeId { get; set; }
        public Nullable<System.DateTime> dtLocacao { get; set; }
        public Nullable<System.DateTime> dtDevolucao { get; set; }
    }
}
